### ISSUE TITLE
SpacetuxSA-0.3.10.zip has a lot of duplicate files

### ISSUE THREAD

**Issue by mheguy** [linuxgurugamer/SpaceTuxSA#2]
SpacetuxSA-0.3.10.zip on spacedock has duplicates of all files. The files are both in `GameData/spacetux` and `GameData/spacetux/SharedAssets`

**Comment by linuxgurugamer** [comment]
ok, thanks, I'll fix it

**Comment by linuxgurugamer** [comment]
Fixed
