### ISSUE TITLE
Wrong file uploaded to SpaceDock

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/SpaceTuxSA#4]
@linuxgurugamer 

I looked for SquigglySpaceResearch but couldn't find a page for it. This isn't SpacetuxSA:

https://spacedock.info/mod/53/SpacetuxSA/download/0.1.3

![image](https://user-images.githubusercontent.com/1559108/70843265-1b463380-1df5-11ea-9aa3-0cc43f691f36.png)

**Comment by linuxgurugamer** [comment]
It was fixed, please reindex it if necessary

**Comment by HebaruSan** [comment]
Looks good, indexing will take care of itself. Thanks.
